Repository alan22222/CITS5505_Agile_Group_Project, pull requests merged in 2025-05, with the labels that each got.

#16 Update README.md for the first 3 points
  README.md
  app/static/css/dashboard.css
  app/static/css/login-reg.css
  app/static/css/style.css
  app/static/css/upload.css
  app/templates/dashboard.html
  app/templates/layout.html
  app/templates/login.html
  app/templates/register.html
  app/templates/upload.html
Labels: documentation, enhancement

#25 created html pages for view share result, updates on routes ,init
  app/forms.py
  app/models.py
  app/routes.py
  app/static/css/results.css
  app/static/plotting/294778a0-4465-40ef-805d-50009d434de1.png
  app/static/plotting/4a55dccf-3b30-40d9-a712-1c1ffff6fe2b.png
  app/static/plotting/618f58e6-a4a6-4aa3-9fad-b9058d6d35db.png
  app/static/plotting/84c2c059-a50f-4919-94d0-0257dabfeb77.png
  app/static/plotting/kmeans_radar_12-38-33_07-05-2025.png
  app/templates/layout.html
  app/templates/results.html
  app/templates/select_model.html
  app/templates/shared_results.html
  app/templates/view.html
  instance/database.db
  requirements.txt
Labels: enhancement, frontend, backend

#33 Updates on pages ,migration folder, chatgpt integration..
  app/routes.py
  app/static/ml_model/K_means.py
  app/static/ml_model/LinearRegression.py
  app/static/ml_model/SVM_classifier.py
  app/templates/dashboard.html
  app/templates/layout.html
  app/templates/results.html
  migrations/__pycache__/env.cpython-39.pyc
  migrations/versions/028fada59365_add_graph_path_to_uploadeddata.py
  migrations/versions/9a55ded658ec_add_uploadeddata_modelrun_sharedresult_.py
  migrations/versions/__pycache__/028fada59365_add_graph_path_to_uploadeddata.cpython-39.pyc
  migrations/versions/__pycache__/9a55ded658ec_add_uploadeddata_modelrun_sharedresult_.cpython-39.pyc
  migrations/versions/__pycache__/eea7f9f2c8d6_initial_migration_with_user_model_only.cpython-39.pyc
  migrations/versions/eea7f9f2c8d6_initial_migration_with_user_model_only.py
Labels: bug, backend

#38 add 2 selenium test (register and invalid login); update the README.md
  .env
  README.md
  app/__init__.py
  app/routes.py
  app/static/css/sharedresults.css
  app/static/css/style.css
  app/static/css/viewresult.css
  app/templates/dashboard.html
  app/templates/layout.html
  app/templates/shared_results.html
  config.py
  tests/selenium_test.py
Labels: bug, documentation, enhancement, help wanted

#41 bug fix : api key fetch from .env cause internal server error fixed it
  app/routes.py
  app/static/css/viewresult.css
  app/static/ml_model/GPT_result_analysation.py
  app/static/ml_model/GPTassistant.py
  app/templates/view.html
Labels: bug, backend

#45 update README.md, and amended view page styling.
  README.md
  app/static/css/viewresult.css
  app/templates/view.html
Labels: documentation, enhancement, frontend
